[workspace]
resolver = "2"
members = [
    "crates/tempeh-model",
    "crates/tempeh-control",
    "crates/tempeh-sim",
    "crates/tempeh-pet",
    "crates/tempeh-runtime",
    "crates/tempeh-protocol",
    "crates/tempeh-host",
    "crates/tempeh-firmware-esp32",
]
default-members = [
    "crates/tempeh-model",
    "crates/tempeh-control",
    "crates/tempeh-sim",
    "crates/tempeh-pet",
    "crates/tempeh-runtime",
    "crates/tempeh-protocol",
    "crates/tempeh-host",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tempeh-model = { path = "crates/tempeh-model" }
tempeh-control = { path = "crates/tempeh-control" }
tempeh-sim = { path = "crates/tempeh-sim" }
tempeh-pet = { path = "crates/tempeh-pet" }
tempeh-runtime = { path = "crates/tempeh-runtime" }
tempeh-protocol = { path = "crates/tempeh-protocol" }
serialport = "4"
ctrlc = "3"
chrono = "0.4"
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-stream = "0.3"
futures-util = "0.3"
ureq = "2"
anyhow = "1"
esp-idf-hal = "0.45"
esp-idf-svc = "0.51"
esp-idf-sys = { version = "0.36", features = ["binstart"] }
embedded-svc = "0.28"
log = "0.4"
embuild = "0.33"

[profile.release.package.tempeh-firmware-esp32]
opt-level = "s"
debug = true
strip = false
codegen-units = 1
