[package]
name = "tempeh-os"
version = "0.1.0"
edition = "2024"

[dependencies]
tempeh-model = { path = "crates/tempeh-model" }
tempeh-sim = { path = "crates/tempeh-sim" }
tempeh-control = { path = "crates/tempeh-control" }
tempeh-pet = { path = "crates/tempeh-pet" }
serialport = "4"
ctrlc = "3"
chrono = "0.4"

[workspace]
members = [
    "crates/tempeh-model",
    "crates/tempeh-sim",
    "crates/tempeh-control",
    "crates/tempeh-pet",
]

exclude = [
    "firmware/esp32-temperature-bridge",
]
